// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Create(arg1) {
  return window['go']['controller']['BuildProject']['Create'](arg1);
}

export function Delete(arg1) {
  return window['go']['controller']['BuildProject']['Delete'](arg1);
}

export function List(arg1, arg2, arg3) {
  return window['go']['controller']['BuildProject']['List'](arg1, arg2, arg3);
}

export function Modify(arg1) {
  return window['go']['controller']['BuildProject']['Modify'](arg1);
}
