// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RunCode(arg1:string):Promise<void>;

export function TestRunCode(arg1:string,arg2:string):Promise<void>;
