// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function RunCode(arg1) {
  return window['go']['controller']['Code']['RunCode'](arg1);
}

export function TestRunCode(arg1, arg2) {
  return window['go']['controller']['Code']['TestRunCode'](arg1, arg2);
}
