// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDocsContent(arg1) {
  return window['go']['controller']['Docs']['GetDocsContent'](arg1);
}

export function GetDocsTree() {
  return window['go']['controller']['Docs']['GetDocsTree']();
}
