// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DeleteVariable(arg1, arg2, arg3) {
  return window['go']['controller']['Variable']['DeleteVariable'](arg1, arg2, arg3);
}

export function GetVariableList(arg1, arg2) {
  return window['go']['controller']['Variable']['GetVariableList'](arg1, arg2);
}

export function SaveVariable(arg1, arg2, arg3) {
  return window['go']['controller']['Variable']['SaveVariable'](arg1, arg2, arg3);
}
