// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function DeleteVariable(arg1:string,arg2:string,arg3:number):Promise<void>;

export function GetVariableList(arg1:string,arg2:number):Promise<Array<model.Variable>>;

export function SaveVariable(arg1:string,arg2:number,arg3:Array<model.VariableBase>):Promise<void>;
